networks:
  default:
    external: true
    name: cvdp-bridge-cvdp_v1-0-4_nonagentic_code_generation_no_commercial
services:
  direct:
    command: pytest -o cache_dir=/code/rundir/.cache /src/test_runner.py -v -s
    env_file: ./src/.env
    image: ghcr.io/hdl/sim/osvb
    volumes:
    - ./src/:/src/:ro
    working_dir: /code/rundir
