networks:
  default:
    external: true
    name: cvdp-bridge-cvdp_v1-0-4_nonagentic_code_generation_no_commercial
services:
  test:
    command: pytest -sv -o cache_dir=/code/rundir/.cache /src/test_runner.py
    env_file:
    - ./src/.env
    image: ghcr.io/hdl/sim/osvb
    volumes:
    - ./src/:/src
    working_dir: /code/rundir/
