networks:
  default:
    external: true
    name: cvdp-bridge-cvdp_v1-0-2_nonagentic_code_generation_no_commercial
services:
  direct:
    build: .
    command: pytest -s --log-cli-level=INFO -o cache_dir=/rundir/harness/.cache /src/test_runner.py
      -v
    env_file: ./src/.env
    volumes:
    - ./src/:/src/:ro
