networks:
  default:
    external: true
    name: cvdp-bridge-cvdp_v1-0-2_nonagentic_code_generation_no_commercial
services:
  direct:
    command: pytest --log-cli-level=INFO -o cache_dir=/code/rundir/.cache -sv /src/test_runner.py
    env_file: ./src/.env
    image: ghcr.io/hdl/sim/osvb
    volumes:
    - ./src/:/src/:ro
    working_dir: /code/rundir
